#!/bin/bash
set -e

arg=$@
delimiter=--
s=$arg$delimiter
array=();
while [[ $s ]]; do
    if [[ ${s%%"$delimiter"*} == pods* ]]; then
        array+=( "${s%%"$delimiter"*}" );
    fi
    s=${s#*"$delimiter"};
done;

POD_LIST=${array[0]/pods /}

while [[ $# -gt 0 ]]
do
    key="$1"

    case $key in
        -t|--tail)
        TAIL="$2"
        shift # past argument
        shift # past value
        ;;
        -g|--grep)
        GREP="$2"
        shift # past argument
        shift # past value
        ;;
        -l|--label)
        LABEL="$2"
        shift # past argument
        shift # past value
        ;;
        *)
        shift # past argument
        ;;
    esac
done

# Continue with --pods argument when both --pods and --label are passed
# Output from both arguments to be concatenated in the future
if [[ ! -z "${POD_LIST}" && ! -z "${LABEL}" ]]; then
    echo "Both --pods and --label arguments passed. Ignoring labels and continue with --pods arguments"
    unset LABEL
fi

function kill_kubectl_processes {
	kill 0
}

trap kill_kubectl_processes EXIT SIGTERM

if hash kubectl 2>/dev/null; then
    KUBECTL_BIN=${KUBECTL_BIN:-"kubectl"}
elif ! hash ${KUBECTL_BIN}; then
    echo >&2 "kubectl is not installed"
    exit 1
fi

if [[ -z "${POD_LIST}" && ! -z "${LABEL}" ]]; then
    POD_LIST="$(kubectl get pods -l="${LABEL}" | awk '{print $1}' | grep -v 'NAME')"
    POD_LIST="${POD_LIST//$'\n'/ }"
fi

IFS=' ' read -r -a PODS <<< "$POD_LIST"
echo "Tailing pods ${PODS[@]}"

KUBE_LOG="${KUBECTL_BIN} logs -f %pod%"

for pod in "${PODS[@]}"
do
    COMMAND+=${KUBE_LOG/\%pod\%/$pod}
    if [[ ! -z "${TAIL}" ]]; then
        COMMAND+=" --tail=${TAIL}"
    fi
    if [[ ! -z "${GREP}" ]]; then
        COMMAND+=" | grep ${GREP}"
    fi
    COMMAND+=" & "
done

COMMAND=${COMMAND%& }
echo ${COMMAND}
eval "${COMMAND}"
